---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Task 1 - Initial submission"

parameters: 
  uid:
    name: uid
    in: path
    description: UID of a process
    type: string
    required: true
  process:
    name: process 
    in: body
    description: Process description
    required: true
    schema:
      $ref: '#/definitions/Process'


paths:

  /:
    get:
      operationId: "shipit.api.get_root"
      responses:
        200:
          description: List of UIDs for all processes of task1.
          schema:
            type: array
            items:
              type: string

  /process/{uid}:
    get:
      operationId: "shipit.api.get_process"
      description: Process status
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        200:
          description: Status of the process
        404:
          description: Process not found

    post:
      operationId: "shipit.api.post_process"
      description: Start a process
      parameters:
        - $ref: '#/parameters/uid'
        - $ref: '#/parameters/process'
          # TODO: callback
      responses:
        200:
          description: Start the task
        404:
          description: Process already exists

    delete:
      operationId: "shipit.api.delete_process"
      description: Stop a process
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        200:
          description: Process stopped
        404:
          description: Process not found

    patch:
      operationId: "shipit.api.patch_process"
      description: Update a process
      parameters:
        - $ref: '#/parameters/uid'
        - $ref: '#/parameters/process'
      responses:
        200:
          description: Process edited
        404:
          description: Process not found


definitions:
  
  Process:
    type: object
    required:
      - product_name
    properties:
      product_name:
        type: string
  
  #  put:
  #    parameters:
  #      - name: body
  #        in: body
  #        required: true
  #        description: TODO
  #        scheme:
  #          type: string
  #          #type: object
  #          #items:
  #          #  result0: 
  #          #    $ref: '#/definitions/Result0'
  #    responses:
  #      200:
  #        description: Start the task
  #        scheme:

  #          $ref: '#/definitions/XXX'
  #      #400:
  #      #  description: Extra validation
  #      #  scheme:
  #      #    type: object
  #      #    schema:
  #      #      type:
  #      #        type: string
  #      #      message:
  #      #        type: string
  #  post:
  #    responses:
  #      200:
  #        description: Restart of the task
  #        schema:
  #  delete:
  #    responses:
  #      200:
  #        description: Stop of the task



