version: 0
metadata:
  name: "Mozilla Releng"
  description: "Mozilla Releng Services"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
    payload:
      maxRunTime: 7200 # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      command:
        - "nix-shell"
        - "-p"
        - "curl"
        - "gnumake"
        - "gnutar"
        - "--run"
        - "\"curl -L https://github.com/garbas/mozilla-releng/archive/${GITHUB_HEAD_SHA}.tar.gz\""
    metadata:
      name: "make build-apps"
      description: "Build and run tests for all projects"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
