version: 0
metadata:
  name: "Mozilla RelEng"
  description: "Mozilla RelEng Services"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:

  #
  # master | releng
  #  - test and build releng_* apps
  #

  - metadata:
      name: "releng_docs"
      description: "Test, build and deploy Releng Frontend"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    scopes:
      - secrets:get:garbage/garbas/temp-releng-services
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
        branches:
          - master
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200 # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        APP: "releng_docs"
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/garbage/garbas/temp-releng-services"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.gnumake nixpkgs.curl && mkdir /src && cd /src && curl -L https://github.com/garbas/mozilla-releng/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd mozilla-releng-$GITHUB_HEAD_SHA && ./.taskcluster.sh"

  - metadata:
      name: "releng_frontend"
      description: "Test, build and deploy Releng Frontend"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    scopes:
      - secrets:get:garbage/garbas/temp-releng-services
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
        branches:
          - master
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200 # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        APP: "releng_frontend"
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/garbage/garbas/temp-releng-services"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.gnumake nixpkgs.curl && mkdir /src && cd /src && curl -L https://github.com/garbas/mozilla-releng/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd mozilla-releng-$GITHUB_HEAD_SHA && ./.taskcluster.sh"

  - metadata:
      name: "releng_clobberer"
      description: "Test, build and deploy RelEng Clobberer service"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    scopes:
      - secrets:get:garbage/garbas/temp-releng-services
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
        branches:
          - master
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200 # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        APP: "releng_clobberer"
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/garbage/garbas/temp-releng-services"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.gnumake nixpkgs.curl && mkdir /src && cd /src && curl -L https://github.com/garbas/mozilla-releng/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd mozilla-releng-$GITHUB_HEAD_SHA && ./.taskcluster.sh"

  #
  # staging | releng
  #

  - metadata:
      name: "releng_docs"
      description: "Test, build and deploy Releng Frontend"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    scopes:
      - secrets:get:garbage/garbas/temp-releng-services
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - staging
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200 # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        APP: "releng_docs"
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/garbage/garbas/temp-releng-services"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.gnumake nixpkgs.curl && mkdir /src && cd /src && curl -L https://github.com/garbas/mozilla-releng/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd mozilla-releng-$GITHUB_HEAD_SHA && ./.taskcluster.sh"

  - metadata:
      name: "releng_frontend"
      description: "Test, build and deploy Releng Frontend"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    scopes:
      - secrets:get:garbage/garbas/temp-releng-services
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - staging
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200 # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        APP: "releng_frontend"
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/garbage/garbas/temp-releng-services"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.gnumake nixpkgs.curl && mkdir /src && cd /src && curl -L https://github.com/garbas/mozilla-releng/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd mozilla-releng-$GITHUB_HEAD_SHA && ./.taskcluster.sh"

  - metadata:
      name: "releng_clobberer"
      description: "Test, build and deploy RelEng Clobberer service"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    scopes:
      - secrets:get:garbage/garbas/temp-releng-services
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - staging
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200 # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        APP: "releng_clobberer"
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/garbage/garbas/temp-releng-services"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.gnumake nixpkgs.curl && mkdir /src && cd /src && curl -L https://github.com/garbas/mozilla-releng/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd mozilla-releng-$GITHUB_HEAD_SHA && ./.taskcluster.sh"

  #
  # master | shipit
  #


  - metadata:
      name: "shipit_frontend"
      description: "Test, build and deploy ShipIt Frontend"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    scopes:
      - secrets:get:garbage/garbas/temp-releng-services
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
        branches:
          - master
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200 # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        APP: "shipit_frontend"
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/garbage/garbas/temp-releng-services"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.gnumake nixpkgs.curl && mkdir /src && cd /src && curl -L https://github.com/garbas/mozilla-releng/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd mozilla-releng-$GITHUB_HEAD_SHA && ./.taskcluster.sh"

  - metadata:
      name: "shipit_dashboard"
      description: "Test, build and deploy ShipIt Dashboard service"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    scopes:
      - secrets:get:garbage/garbas/temp-releng-services
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
        branches:
          - master
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200 # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        APP: "shipit_dashboard"
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/garbage/garbas/temp-releng-services"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.gnumake nixpkgs.curl && mkdir /src && cd /src && curl -L https://github.com/garbas/mozilla-releng/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd mozilla-releng-$GITHUB_HEAD_SHA && ./.taskcluster.sh"
