---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Clobberer"
paths:

  /buildbot:

    get:
      operationId: "relengapi_clobberer.api.get_buildbot"
      responses:
        200:
          description: An array of branches
          schema:
            type: array
            items:
              $ref: '#/definitions/Branch'

    post:
      operationId: "relengapi_clobberer.api.post_buildbot"
      parameters:
        - name: body
          in: body
          description: List of Builds to clobber.
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Builder'
      responses:
        200:
          description: Builders clobbered
          schema:
            type: array
            items:
              $ref: '#/definitions/Success'
        500:
          description: Something went wrong when clobbering builders
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'

  /taskcluster:

    get:
      operationId: "relengapi_clobberer.api.get_taskcluster"
      responses:
        200:
          description: An array of branches

    post:
      operationId: "relengapi_clobberer.api.post_taskcluster"
      responses:
        200:
          description: Branches clobbered

definitions:

  Success:
    type: string 

  Error:
    type: object
    required:
      - error_title
    properties:
      error_title:
        type: string
      error_message:
        type: string

  Branch:
    type: object
    required:
      - name
      - builders
    properties:
      name:
        type: string
      builders:
        type: array
        description: Builders per branch
        items:
          $ref: '#/definitions/Builder'

  Builder:
    type: object
    required:
      - name
      - branch
      - builddir
      - slave
      - lastclobber
      - who
    properties:
      name:
        type: string
      branch:
        type: string
      builddir:
        type: string
      slave:
        type: string
      lastclobber:
        type: integer
      who:
        type: string
